# Generated by Django 4.1.3 on 2023-08-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0003_subject_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='classes',
        ),
    ]
