# Generated by Django 4.1.3 on 2023-08-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0004_remove_subject_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
