# Generated by Django 4.1.3 on 2023-08-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0005_subject_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='subject_logos/'),
        ),
    ]
