# Generated by Django 4.1.3 on 2023-08-22 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0007_eventimages_alter_subject_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventImages',
            new_name='EventImage',
        ),
    ]
