# Generated by Django 4.1.3 on 2023-08-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0009_event_eventimage_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='event_img/'),
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
