# Generated by Django 4.1.3 on 2023-08-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0010_event_images_delete_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
