# Generated by Django 4.1.3 on 2023-08-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0013_eventimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='images',
        ),
    ]
