# Generated by Django 4.2.4 on 2023-08-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0014_remove_event_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='images',
            field=models.ImageField(blank=True, default='cmsNvsd_kjzx_jdn', null=True, upload_to='event_img/'),
        ),
    ]
